import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

import { Separator } from '@/components/ui/separator'
import {NavigationBar} from "@/components/navbar";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en" className={'dark'}>
      <body className={inter.className}>
      <NavigationBar/>
      <br />
      <div className="container mx-auto px-4">{children}</div>
      </body>
      </html>
  )
}
